name: Build and Deploy Docker Compose

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker-compose -f sdtbuBOT/docker-compose.yml build
        docker-compose -f sdtbuBOT/docker-compose.yml push

    - name: Deploy Docker Compose services
      run: |
        docker-compose -f sdtbuBOT/docker-compose.yml up -d
