name: Build and Deploy Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Log in to Alibaba Cloud Container Registry
      run: |
        echo ${{ secrets.ALICLOUD_PASSWORD }} | docker login --username ${{ secrets.ALICLOUD_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -f sdtbuBOT/Dockerfile -t registry.cn-hangzhou.aliyuncs.com/ricxx/wxbot:latest --build-arg CONFIGURATION=Release .
        docker push registry.cn-hangzhou.aliyuncs.com/ricxx/wxbot:latest

    - name: Deploy Docker Container
      run: |
        docker run -d --name sdtbubot -p 80:8080 registry.cn-hangzhou.aliyuncs.com/ricxx/wxbot:latest
