# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore sdtbuBOT.sln
    - name: Build
      run: dotnet build sdtbuBOT.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test sdtbuBOT.sln --no-build --verbosity normal --configuration Release
    - name: Publish
      run: dotnet publish sdtbuBOT.sln --no-build --configuration Release --output ./publish
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./publish
